### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by panmona** [hkan/tic-tac-vue#21]
The demo page cannot be found anymore. You could consider to host it on GitHub Pages.

**Comment by andreaselia** [comment]
Not sure GitHub Pages would allow us to run the socket.io server.

**Comment by panmona** [comment]
Ah no that won't work but the frontend should work.

**Comment by panmona** [comment]
The demo still doesn't work though. So this isn't solved.

**Comment by hkan** [comment]
That's true. I'll come up with something in a few days. Buried in plenty of work right now.

**Comment by panmona** [comment]
@hkan Sounds good. No stress :)

**Comment by hkan** [comment]
Set up a Heroku app and updated repo. It _barely_ works, but it's something.

![It's something meme](http://i0.kym-cdn.com/entries/icons/original/000/005/600/its-something.jpg)
